# Generated by Django 3.1.6 on 2021-02-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodsbo', '0002_dodsbo_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodsbo',
            name='image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
