# Generated by Django 3.1.6 on 2021-03-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodsbo', '0003_auto_20210221_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodsbo',
            name='statusoppgjør',
            field=models.CharField(choices=[('PÅGÅR', 'Pågår'), ('AVSLUTTET', 'Avsluttet')], default='PÅGÅR', max_length=10),
        ),
    ]
