# Generated by Django 3.1.6 on 2021-04-04 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dodsbo', '0004_dodsbo_statusoppgjør'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dodsbo',
            options={'verbose_name': 'Dødsbo', 'verbose_name_plural': 'Dødsbo'},
        ),
        migrations.AlterField(
            model_name='dodsbo',
            name='descritption',
            field=models.TextField(verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='dodsbo',
            name='image',
            field=models.ImageField(null=True, upload_to='pics', verbose_name='Bilde'),
        ),
        migrations.AlterField(
            model_name='dodsbo',
            name='members',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL, verbose_name='Brukere'),
        ),
        migrations.AlterField(
            model_name='dodsbo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='dodsbo',
            name='statusoppgjør',
            field=models.CharField(choices=[('PÅGÅR', 'Pågår'), ('ENUKEIGJEN', 'En uke igjen'), ('AVSLUTTET', 'Avsluttet')], default='PÅGÅR', max_length=10),
        ),
    ]
