# Generated by Django 3.1.6 on 2021-03-08 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', ' 0014_auto_20210222_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='user_id',
        ),
        migrations.AddField(
            model_name='choice',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
        migrations.AddField(
            model_name='choice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Prioritering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prioritering', models.CharField(choices=[('1', 'Ikke viktig'), ('2', 'Litt viktig'), ('3', 'Interessert'), ('4', 'Ganske interessert'), ('5', 'Veldig interessert')], default='1', max_length=1)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prioritering',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
