# Generated by Django 3.1.6 on 2021-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_choice',
            field=models.CharField(choices=[('K', 'Keep'), ('D', 'Donate'), ('T', 'Throw')], default='', max_length=30),
        ),
    ]
