# Generated by Django 3.1.6 on 2021-03-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_auto_20210308_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prioritering',
            old_name='Prioritering',
            new_name='PrioriteringsValg',
        ),
    ]
