# Generated by Django 3.1.6 on 2021-03-11 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dodsbo', '0003_auto_20210221_1235'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210308_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Valg',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Eiendel',
        ),
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('kommentar', models.TextField()),
                ('dato_laget', models.DateTimeField(auto_now_add=True)),
                ('aktiv', models.BooleanField(default=False)),
                ('eiendel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentarer', to='main.eiendel')),
            ],
            options={
                'ordering': ['dato_laget'],
            },
        ),
    ]
