# Generated by Django 3.1.6 on 2021-03-14 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20210311_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prioritering',
            old_name='item',
            new_name='itemprio',
        ),
        migrations.RenameField(
            model_name='prioritering',
            old_name='user',
            new_name='userprio',
        ),
        migrations.AlterUniqueTogether(
            name='prioritering',
            unique_together={('userprio', 'itemprio')},
        ),
    ]
