# Generated by Django 3.1.6 on 2021-02-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210213_1453'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
    ]
