# Generated by Django 3.1.6 on 2021-03-15 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20210311_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kommentar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kommentar',
            name='navn',
        ),
        migrations.AddField(
            model_name='kommentar',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
