# Generated by Django 3.1.6 on 2021-03-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dodsbo', '0003_auto_20210221_1235'),
        ('main', '0004_auto_20210315_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='kommentar',
            name='dodsbo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dodsbo.dodsbo'),
        ),
    ]
