# Generated by Django 3.1.6 on 2021-03-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_kommentar_dodsbo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kommentar',
            name='dodsbo',
        ),
    ]
