# Generated by Django 3.1.6 on 2021-02-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210218_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_choice',
        ),
    ]
