# Generated by Django 3.1.6 on 2021-03-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210314_1150'),
        ('main', '0006_remove_kommentar_dodsbo'),
    ]

    operations = [
    ]
