# Generated by Django 3.1.6 on 2021-03-25 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_merge_20210317_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tildelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eiendel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eiendel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
