# Generated by Django 3.1.6 on 2021-02-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_item_item_choice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
    ]
