# Generated by Django 3.1.6 on 2021-02-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210218_1358'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
    ]
