# Generated by Django 3.1.6 on 2021-04-04 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dodsbo', '0005_auto_20210404_2221'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_tildelt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eiendel',
            options={'verbose_name': 'Eiendel', 'verbose_name_plural': 'Eiendeler'},
        ),
        migrations.AlterModelOptions(
            name='kommentar',
            options={'ordering': ['dato_laget'], 'verbose_name': 'Kommentar', 'verbose_name_plural': 'Kommentarer'},
        ),
        migrations.AlterModelOptions(
            name='prioritering',
            options={'verbose_name': 'Prioritering', 'verbose_name_plural': 'Prioriteringer'},
        ),
        migrations.AlterModelOptions(
            name='valg',
            options={'verbose_name': 'Valg', 'verbose_name_plural': 'Valg'},
        ),
        migrations.AlterField(
            model_name='eiendel',
            name='dodsbo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dodsbo.dodsbo', verbose_name='Dødsbo'),
        ),
        migrations.AlterField(
            model_name='eiendel',
            name='item_choice',
            field=models.CharField(choices=[('K', 'Behold'), ('D', 'Doner'), ('T', 'Kast')], default='K', max_length=1, verbose_name='Valg'),
        ),
        migrations.AlterField(
            model_name='eiendel',
            name='item_desc',
            field=models.CharField(max_length=300, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='eiendel',
            name='item_image',
            field=models.ImageField(blank=0, null=True, upload_to='', verbose_name='Bilde'),
        ),
        migrations.AlterField(
            model_name='eiendel',
            name='item_name',
            field=models.CharField(max_length=30, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='kommentar',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bruker'),
        ),
        migrations.AlterField(
            model_name='prioritering',
            name='PrioriteringsValget',
            field=models.CharField(choices=[('1', 'Ikke viktig'), ('2', 'Litt viktig'), ('3', 'Interessert'), ('4', 'Ganske interessert'), ('5', 'Veldig interessert')], default='1', max_length=1, verbose_name='Prioritering'),
        ),
        migrations.AlterField(
            model_name='prioritering',
            name='itemprio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.eiendel', verbose_name='Eiendel'),
        ),
        migrations.AlterField(
            model_name='prioritering',
            name='userprio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bruker'),
        ),
        migrations.AlterField(
            model_name='valg',
            name='choice',
            field=models.CharField(choices=[('K', 'Behold'), ('D', 'Doner'), ('T', 'Kast')], default='K', max_length=1, verbose_name='Valg'),
        ),
        migrations.AlterField(
            model_name='valg',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='valg',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.eiendel', verbose_name='Eiendel'),
        ),
        migrations.AlterField(
            model_name='valg',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bruker'),
        ),
    ]
