# Generated by Django 3.1.6 on 2021-02-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dodsbo', '0002_dodsbo_members'),
        ('main', '0009_auto_20210218_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dodsbo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dodsbo.dodsbo'),
        ),
    ]
