# Generated by Django 3.1.6 on 2021-04-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210404_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tildelt',
            options={'verbose_name_plural': 'Tildelt'},
        ),
    ]
