# Generated by Django 3.1.6 on 2021-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210218_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_choice',
            field=models.CharField(choices=[('K', 'Keep'), ('D', 'Donate'), ('T', 'Throw')], default='K', max_length=1),
        ),
    ]
