# Generated by Django 3.1.6 on 2021-02-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_item_item_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('K', 'Keep'), ('D', 'Donate'), ('T', 'Throw')], default='K', max_length=1)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
